### ISSUE TITLE
Clearing cache when a model is saved

### ISSUE THREAD

**Issue by absolux** [qawemlilo/nodeza#96]
Hi @qawemlilo
I was wondering why would you clear the app cache when a model is saved ?

**Comment by qawemlilo** [comment]
@absolux I am using [express-redis-cache](https://github.com/rv-kip/express-redis-cache) for caching and I discovered that when you made updates the view would remain unchanged. This was a quick fix solution, the alternative would be to clear the cache for only the views associated with that model. 

I'm open to suggestions for a better solution.

**Comment by absolux** [comment]
Caching views is not the responsibility of models, but controllers.
After reading the express-redis-cache documentation, it is possible to create a named caches for example `post-123`, and delete only that cache in controller method, when the post with id 123 is updated.

**Comment by qawemlilo** [comment]
Yes you are correct, I am breaking the MVC rules - will create a to-do list and put it there.
